version: '4.1.1'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: fixflow-postgres
    restart: always
    environment:
      POSTGRES_DB: fixflow_db
      POSTGRES_USER: fixflow_user
      POSTGRES_PASSWORD: fixflow_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: